### ISSUE TITLE
Yubikey. "Invalid Composite Key" error

### ISSUE THREAD

**Issue by Sergio9182** [pp3345/ykDroid#13]
Keepass2android 1.07b is the best! But I can't get ykdroid to completely work.

This is my setup and what is happening:
-Running Android 10
-I setup on my Windows 10 PC a Yubikey 5 NFC and a yubikey USB C with same secret key and the challenge configuration on slot 2
-Database .kdbx is setup with same secret keys as Yubikey on Windows using Keepass 2.45. And it opens every single time using the USB A and C available on the yubikeys.
-I copied .kdbx file to my Android phone 
-ykdroid is installed
-when trying to open .kdbx I select password+Challenge KeepassXC
-It asks for key, slot 2.
-after swiping NFC key or inserting USB C key it
shows Loading database transforming master key
-After a second or two it shows Composite key invalid.

But if...
I choose in keepass2android Password+challenge RECOVERY and using the same password as above and typing the same secret key set on the yubikey, then it works great and it opens the .kdbx file with no other issues.

Anyone out there that can tell me what I'm missing in the setup of the yubikey or ykdroid?

Thanks!!

**Comment by pp3345** [comment]
You said that you used KeePass 2.45 for setup. Therefore, you should select "Password + Challenge Response" in KP2A, **not** "Password + Challenge Response for KeePassXC". Note that you probably also have a .xml file accompanying the .kdbx database which you should also copy to your phone.

Can you test whether this works?

**Comment by Sergio9182** [comment]
Sorry, it didn't work. These are the steps I followed:
-I found the matching .xml file in my windows laptop in the same directory as the .kdbx file.-I copied it to same directory as the .kdbx file on the phone-tried using the "Password + Challege Response"-Nothing happens when I press Unlock. (same happened before copying .xml file to the phone)-Then tried using the "Password + Challenge Response for Keepass XC"-Pressing unlock, it asks for Key (slot 2), I get same message Loading database (transforming key) and then the error "Invalid Composite Key". I tried with both the NFC and USB C key.
-Tried again with Keepass on Win laptop and it continues to work fine.
Any ideas??




    On Thursday, July 16, 2020, 5:50:30 AM EDT, Yussuf Khalil <notifications@github.com> wrote:  
 
 


You said that you used KeePass 2.45 for setup. Therefore, you should select "Password + Challenge Response" in KP2A, not "Password + Challenge Response for KeePassXC". Note that you probably also have a .xml file accompanying the .kdbx database which you should also copy to your phone.

Can you test whether this works?

**Comment by pp3345** [comment]
You'll need to press the "Load OTP auxiliary file" button in order to load the .xml file before trying to unlock.

**Comment by Sergio9182** [comment]
Now it works only the first time I open a freshly created database, but fails every time after that when I try to load the OTP auxiliar file an error pops-up "Could not load Auxiliary Challenge File, Please use keeChallenge plugin in Keepass 2.x PC....."
Steps:-I uninstalled ykdroid and KP2A and Reinstalled them both-Created a new database on Keepass PC and set it for challenge response-Made no changes to Yubikey configuration (i.e. kept secret key the same)-Copied new database and .xml file to phone-Selected database in KP2A, "Password + Challenge Response", Entered Password-Pressed "load OTP auxiliar file" and selected .xml file-It asked for Yubikey slot 2 and after it gave me an error asking to unplug yubikey and plug back in, i did so, and then pressed Unlock and it opened.

Then I:
-Locked database and closed K2PA-Reopened KP2A, set Password+Challenge Response-When trying to load .xml file the error pops-up.


    On Friday, July 17, 2020, 7:26:51 AM EDT, Yussuf Khalil <notifications@github.com> wrote:  
 
 


You'll need to press the "Load OTP auxiliary file" button in order to load the .xml file before trying to unlock.

**Comment by pp3345** [comment]
You said you're using KP2A 1.07b. The current release is 1.08. Can you try with a newer version of KP2A?

**Comment by Sergio9182** [comment]
Still same issue.

I removed KP2A 1.07b, a web fill plugin for KP2A I had installed and ykdroid, reinstalled only KP2A 1.08 pre-release3 and ykdroid, re-started phone (just in case).
Re-configured Yubikey 5 NFC on slot 2 with New secret key. Created brand New database on KeePass in PC. Transferred the new .kdbx and .xml files to phone.

The first time I load .xml file it works flawlessly, this time I said no to autofill (to test something different). Trying to load .xml file after that gives me the same error: "Could not load auxiliary file....".  

I even tried: 
-loading file first and entering password after and viceversa,-removed database from recent database list in KP2A main screen,-rebooting phone,-turned on show backups on slider at bottom of screen and removed the database from the list,-moved both .kbdx and .xml file to different folder and tried to open from there.

    On Saturday, July 18, 2020, 7:00:24 AM EDT, Yussuf Khalil <notifications@github.com> wrote:  
 
 


You said you're using KP2A 1.07b. The current release is 1.08. Can you try with a newer version of KP2A?

**Comment by pp3345** [comment]
Sorry, but this seems to be a KP2A issue, not a ykDroid one. Please open an issue over at https://github.com/PhilippC/keepass2android. There is nothing I can do for you, I am sorry.
