### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [pp3345/ykDroid#17]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
> mondlicht-und-sterne closed this as completed on Feb 11, 2021

No screenshots:

![Image](https://github.com/user-attachments/assets/7019f4f0-7577-4f45-8883-af618faa3e73)
