### ISSUE TITLE
always return a result

### ISSUE THREAD

**Issue by PhilippC** [pp3345/ykDroid#2]
If the ChallengeResponseActivity is called with startActivityForResult, it should always return a result. I suggest to call setResult with the cancelled result code. This is important for cases where users "cancel" the operation by clicking the back button.

**Comment by pp3345** [comment]
I don't quite understand the problem here. According to the Android documentation (https://developer.android.com/reference/android/app/Activity.html#RESULT_CANCELED), RESULT_CANCELED already is the default return code. I've confirmed with some quick tests that the result for the ykDroid intent indeed gets set to RESULT_CANCELED in case the user presses the back button. Are there other cases where this doesn't work?

**Comment by PhilippC** [comment]
sorry, my fault. I remembered there was something wrong in the Yubichallenge implementation and I thought that was it, but you're right. It was a missing "finish()" call in the onBackPressed(), not sure if this is relevant for ykDroid.
In the 1.06-pre1 (https://play.google.com/apps/testing/keepass2android.keepass2android), Keepass2Android will either use ykDroid or its own implementation if ykDroid is not found. With my Yubikey NEO I couldn't get ykDroid to work. I only heard the sound as if no NFC listener was active. Can you please check if it works for you?

**Comment by pp3345** [comment]
Yes, it actually works fine for me. Using the beta from Google Play and ykDroid, I can successfully unlock my database. Is there any output from ykDroid in logcat?

**Comment by PhilippC** [comment]
no, I don't see any.

**Comment by pp3345** [comment]
Well, that's strange. Did you install ykDroid from Google Play or have you compiled it yourself? Do you have any other devices for testing?

**Comment by PhilippC** [comment]
I tried both (Playstore and Android Studio) on my Pixel without success. Just tested on a Samsung Galaxy S5, same behavior. Maybe you can add some logging so I can see what's going on? Should I ask other testers for testing?

**Comment by PhilippC** [comment]
Or could it be related to my Yubikey configuration? Can you describe how you configured it?

**Comment by pp3345** [comment]
It might be related to the selected slot. ykDroid uses slot 2 per default (like KeeChallenge). If you have configured challenge-response in slot 1, you'll need to select that in the UI before swiping the YubiKey.

**Comment by PhilippC** [comment]
unfortunately this does not change anything.

**Comment by pp3345** [comment]
I *might* have an idea what's going on, but I am not sure. Can you please try the following APK: https://dev.pp3345.net/ykdroid-debug-signed-3f38214+.apk

It adds some debug output and a small change to NFC handling which might or might not help. In any case, please attach the logcat output from ykDroid after testing.

**Comment by PhilippC** [comment]
it's still not working. I have collected a logcat, but when I swipe the Yubikey, nothing is written to logcat (at least nothing that passes the filter "ykdroid")

07-10 22:04:55.905 29010-29010/net.pp3345.ykdroid D/ykDroid: ConnectionManager initialized
07-10 22:04:55.937 29010-29010/net.pp3345.ykdroid D/ykDroid: waitForYubiKey
07-10 22:04:55.938 29010-29010/net.pp3345.ykdroid D/ykDroid: onCreate complete
07-10 22:04:55.940 29010-29010/net.pp3345.ykdroid D/ykDroid: onActivityStarted USB=1
07-10 22:04:55.947 29010-29010/net.pp3345.ykdroid D/ykDroid: onActivityResumed NFC=2
07-10 22:04:55.794 878-10205/? I/ActivityManager: START u0 {act=net.pp3345.ykdroid.intent.action.CHALLENGE_RESPONSE cmp=net.pp3345.ykdroid/.ChallengeResponseActivity (has extras)} from uid 10103
07-10 22:04:56.141 29010-29017/net.pp3345.ykdroid I/zygote64: Do partial code cache collection, code=125KB, data=112KB
07-10 22:04:56.141 29010-29017/net.pp3345.ykdroid I/zygote64: After code cache collection, code=125KB, data=112KB
07-10 22:04:56.141 29010-29017/net.pp3345.ykdroid I/zygote64: Increasing code cache capacity to 512KB
07-10 22:04:56.180 878-928/? I/ActivityManager: Displayed net.pp3345.ykdroid/.ChallengeResponseActivity: +276ms

**Comment by pp3345** [comment]
Still not sure what exactly is going on, it seems that ykDroid doesn't receive any Intent when swiping the YubiKey. Maybe that's caused by the way the intent filter is defined in ykDroid. Please try this build, it uses intent filter settings that are similar to what YubiChallenge does: https://dev.pp3345.net/ykdroid-3f38214+++-debug.apk

**Comment by PhilippC** [comment]
yep, that's working! Thanks a lot!
I guess I will remove my Yubichallenge port from the app (to get rid of the additional required permission) in the next beta.

**Comment by pp3345** [comment]
Great! I'll push a commit with a fix and an update to Play Store soon, but I'll wait for some feedback on the USB issue from https://github.com/PhilippC/keepass2android/issues/4#issuecomment-403729160 first.

**Comment by PhilippC** [comment]
ykDroid is now the only option to use Yubikey with Keepass2Android (https://github.com/PhilippC/keepass2android/commit/a627dac4b79ff9693e593b07712458ab2aa4ac6f). Please let me know when you have published the update so I can prepare mine.

**Comment by pp3345** [comment]
@PhilippC I've published the update for ykDroid on Google Play now.
