### ISSUE TITLE
Bug: Android 13 broken

### ISSUE THREAD

**Issue by exalented** [pp3345/ykDroid#23]
~~This does not work on Android 13~~
Fixed NFC in my ROM.

**Comment by pp3345** [comment]
Can you elaborate on what exactly isn't working? NFC or USB? What type of YubiKey? What exactly happens when you try to use your YubiKey (e.g., is there any visual response, do you get an error message, ...)? What device model are you using?

**Comment by exalented** [comment]
Apologise for the late response. On my `Yubikey 5 NFC` NFC doesn't seem to be working, but USB is. I am running a custom ROM, so I'm aware it might be something there.

> is there any visual response [with NFC]

Yes, the nfc icon in android 13 at the top right flashes off and then turns back on. The phone doesn't vibrate.

EDIT: I just checked logcat and it looks like the NFC service is dying, sorry for this spam.
