### ISSUE TITLE
Unable to install on Pixel with stock Android 13 and February 2023 Security update

### ISSUE THREAD

**Issue by STRAYDIRT** [pp3345/ykDroid#26]
I am unable to install as the play store is giving me the old "This app isn't available for your device because it was built for an older version of Android." error message. Any chance of an updated build?

**Comment by pp3345** [comment]
I've received another report of this issue last week via e-mail. I am looking into it and will try to provide an update soon-ish. Sorry for the circumstances.

**Comment by STRAYDIRT** [comment]
No need to be sorry, Thank you for the support.

**Comment by gh4YanSi** [comment]
On Samsung phones with Android 13, the exact same message appears. Me and a few friends lost access to Keepass2Android so we keep our fingers crossed... ;)

By the way, I added a translation of strings (PL) maybe someone will find it useful.

Thank you for your support and work!

**Comment by alles-klar** [comment]
I had the same issue today. A possible workaround is the installation with F-Droid.

**Comment by AlejandroRivera** [comment]
Any updates on this issue?

**Comment by rafaelazvdo** [comment]
@AlejandroRivera not yet, for now you will have to use the version downloaded from github or f-droid.

**Comment by pp3345** [comment]
[ykDroid 1.3](https://github.com/pp3345/ykDroid/releases/tag/1.3) with proper support for Android 13 is now available on GitHub. The Play Store release is currently pending review by Google and should appear within the next few days.
