### ISSUE TITLE
Publish on F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [pp3345/ykDroid#6]
I guess I'm speaking for a lot of people when I ask whether you could publish your app on F-Droid. Hence I've already prepared a [Request For Packaging](https://gitlab.com/fdroid/rfp/issues/741) – and hope you support it. Will you? Thanks in advance!

**Comment by pp3345** [comment]
Sure, no problem. Sorry, I don't really know how F-Droid works, is there anything else I have to do apart from expressing my support?

**Comment by IzzySoft** [comment]
@pp3345 Thanks! And no, no "formal process": your saying so suffices. The F-Droid bot already scanned the sources and gave a thumbs-up – so now one of the devs will try to build it and, when all succeeded, your app should be listed [at F-Droid](https://f-droid.org). Might take a little until then – from a few days to a few weeks; F-Droid is a bit understaffed, and all contributors are volunteers …

So thanks a lot, looking forward to see your app there! Until then, it can already be found [in my repo](http://apt.izzysoft.de/fdroid/index/apk/net.pp3345.ykdroid) using the F-Droid client; I've picked the APK from your Github repo here (while F-Droid will pick the source and build an APK from it).

**Comment by pp3345** [comment]
Looks like this finally landed. Thanks a lot!

**Comment by IzzySoft** [comment]
Thanks to you as well, @pp3345! Not that you wonder: I have removed the app from my repo when it was listed in the official one, to avoid confusion (as the signatures won't match).
